site_name: nvg14
site_url: https://nvg14.github.io/
use_directory_urls: false
# Repository
edit_uri: ""

# Configuration
theme:
  name: material
  logo: assets/images/nithin-cropped.png
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search
  - include-markdown
  - table-reader
  - neoteroi.mkdocsoad

extra_css:
  - css/style.css

# Extensions
markdown_extensions:
  - mdx_truly_sane_lists
  - neoteroi.timeline
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
nav:
  - Home: index.md
  - Posts: 
    - "2024": 
      - "Essense of neural network": posts/2024/essense-of-neural-network.md

extra:
  generator: false
