name: Build-Docs
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT2 }}
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.9'
          cache: "pip"
      - name: Installing requirements
        run : pip3 install -r requirements.txt
      - name: Runing Mkdocs
        run : mkdocs build
      - name: coping site files to docs s3 bucket
        run : |
          aws s3 ls --recursive ${{ secrets.AWS_S3_BUCKET_URI }}
          aws s3 cp --recursive site ${{ secrets.AWS_S3_BUCKET_URI }}
      - name: creating invalidation for CDN
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths "/*"